// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SPINbuster.Infrastructure.Persistence;

#nullable disable

namespace SPINbuster.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SpinbusterDbContext))]
    [Migration("20260716180657_KnowledgeEnginePersistenceRc")]
    partial class KnowledgeEnginePersistenceRc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.AiProposalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AbstentionReason")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfidenceBand")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContextManifestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContextManifestId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("GeneratedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InputTokenCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("InspectionSessionId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LatencyMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelDigest")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModelRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputSchemaId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputSchemaVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OutputTokenCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptPackageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptPackageVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferencedSourceIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewDispositionNotes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StructuredPayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("TEXT");

                    b.Property<string>("UncertaintyCodesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationFailuresJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelRunId")
                        .IsUnique();

                    b.HasIndex("ReportId");

                    b.ToTable("ai_proposals", (string)null);
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.AuditEventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubjectType", "SubjectId", "OccurredAtUtc");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.ContextManifestRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextPolicyVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("IncompleteReasonsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InspectionSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManifestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ManifestHash")
                        .IsUnique();

                    b.HasIndex("ProjectId");

                    b.ToTable("context_manifests", (string)null);
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.ContextManifestSourceEntryRecord", b =>
                {
                    b.Property<Guid>("ContextManifestId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorityClassification")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConflictCodesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("InclusionReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuperseded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LimitationNotes")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("ContextManifestId", "Order");

                    b.HasIndex("ProjectId", "SourceType", "SourceId");

                    b.ToTable("context_manifest_source_entries", (string)null);
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.EvidenceAttachmentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapturedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InspectionSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InterpretationSummary")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("InterpretedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("InterpretedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InspectionSessionId");

                    b.ToTable("evidence_attachments", (string)null);
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.FieldNoteRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapturedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InspectionSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InspectionSessionId");

                    b.ToTable("field_notes", (string)null);
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.InspectionSessionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Lifecycle")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("inspection_sessions", (string)null);
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.KnowledgeCitationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CitedRevisionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocatorType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocatorValue")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuotedOrSummarizedText")
                        .HasColumnType("TEXT");

                    b.Property<string>("RevisionContentHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CitedRevisionId");

                    b.HasIndex("CitedRevisionId", "LocatorType", "LocatorValue");

                    b.ToTable("knowledge_citations", (string)null);
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.KnowledgeDocumentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalTitle")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentAuthoritativeRevisionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisciplineOrCategory")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalReferenceNumber")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Lifecycle")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId", "DocumentType");

                    b.ToTable("knowledge_documents", (string)null);
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.KnowledgeDocumentRevisionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptiveNotes")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("IngestionStatus")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("KnowledgeDocumentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KnowledgeSourceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Lifecycle")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RevisionLabel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("SourceAuthority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceSystemReference")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupersededByRevisionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupersedesRevisionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeDocumentId");

                    b.HasIndex("SupersededByRevisionId");

                    b.HasIndex("SupersedesRevisionId");

                    b.HasIndex("KnowledgeDocumentId", "Lifecycle");

                    b.HasIndex("KnowledgeDocumentId", "RevisionLabel")
                        .IsUnique();

                    b.ToTable("knowledge_document_revisions", (string)null);
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.KnowledgeRelationshipRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceOrRationale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RelationshipType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceDocumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceKind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceRevisionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TargetDocumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetKind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TargetRevisionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "SourceKey");

                    b.HasIndex("ProjectId", "TargetKey");

                    b.HasIndex("ProjectId", "SourceKey", "TargetKey", "RelationshipType")
                        .IsUnique();

                    b.ToTable("knowledge_relationships", (string)null);
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.ModelRunAttemptRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("InputTokenCount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LatencyMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ModelRunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OutcomeClassification")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OutputTokenCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawOutput")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawOutputHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelRunId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("model_run_attempts", (string)null);
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.ModelRunRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextManifestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContextManifestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailureClassification")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InspectionSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelDigest")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputSchemaId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputSchemaVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptPackageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptPackageVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestFingerprintHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContextManifestId");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.ToTable("model_runs", (string)null);
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.ProjectRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Lifecycle")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.ReportDraftOperationRecord", b =>
                {
                    b.Property<Guid>("OperationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("TEXT");

                    b.HasKey("OperationId");

                    b.HasIndex("ReportId")
                        .IsUnique();

                    b.ToTable("report_draft_operations", (string)null);
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.ReportEvidenceSourceRecord", b =>
                {
                    b.Property<Guid>("ReportId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EvidenceAttachmentId")
                        .HasColumnType("TEXT");

                    b.HasKey("ReportId", "EvidenceAttachmentId");

                    b.HasIndex("EvidenceAttachmentId");

                    b.ToTable("report_evidence_sources", (string)null);
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.ReportFieldNoteSourceRecord", b =>
                {
                    b.Property<Guid>("ReportId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FieldNoteId")
                        .HasColumnType("TEXT");

                    b.HasKey("ReportId", "FieldNoteId");

                    b.HasIndex("FieldNoteId");

                    b.ToTable("report_field_note_sources", (string)null);
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.ReportRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ApprovedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InspectionSessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Lifecycle")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InspectionSessionId");

                    b.HasIndex("ProjectId");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.ReportSectionRecord", b =>
                {
                    b.Property<Guid>("ReportId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("ReportId", "Position");

                    b.ToTable("report_sections", (string)null);
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.SaveTransactionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PersistedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PreparedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("save_transactions", (string)null);
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.ContextManifestSourceEntryRecord", b =>
                {
                    b.HasOne("SPINbuster.Infrastructure.Persistence.Records.ContextManifestRecord", null)
                        .WithMany("Entries")
                        .HasForeignKey("ContextManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.EvidenceAttachmentRecord", b =>
                {
                    b.HasOne("SPINbuster.Infrastructure.Persistence.Records.InspectionSessionRecord", null)
                        .WithMany("EvidenceAttachments")
                        .HasForeignKey("InspectionSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.FieldNoteRecord", b =>
                {
                    b.HasOne("SPINbuster.Infrastructure.Persistence.Records.InspectionSessionRecord", null)
                        .WithMany("FieldNotes")
                        .HasForeignKey("InspectionSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.InspectionSessionRecord", b =>
                {
                    b.HasOne("SPINbuster.Infrastructure.Persistence.Records.ProjectRecord", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.KnowledgeCitationRecord", b =>
                {
                    b.HasOne("SPINbuster.Infrastructure.Persistence.Records.KnowledgeDocumentRevisionRecord", null)
                        .WithMany("Citations")
                        .HasForeignKey("CitedRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.KnowledgeDocumentRecord", b =>
                {
                    b.HasOne("SPINbuster.Infrastructure.Persistence.Records.ProjectRecord", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.KnowledgeDocumentRevisionRecord", b =>
                {
                    b.HasOne("SPINbuster.Infrastructure.Persistence.Records.KnowledgeDocumentRecord", null)
                        .WithMany("Revisions")
                        .HasForeignKey("KnowledgeDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.KnowledgeRelationshipRecord", b =>
                {
                    b.HasOne("SPINbuster.Infrastructure.Persistence.Records.ProjectRecord", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.ModelRunAttemptRecord", b =>
                {
                    b.HasOne("SPINbuster.Infrastructure.Persistence.Records.ModelRunRecord", null)
                        .WithMany("Attempts")
                        .HasForeignKey("ModelRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.ReportDraftOperationRecord", b =>
                {
                    b.HasOne("SPINbuster.Infrastructure.Persistence.Records.ReportRecord", null)
                        .WithMany("Operations")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.ReportEvidenceSourceRecord", b =>
                {
                    b.HasOne("SPINbuster.Infrastructure.Persistence.Records.ReportRecord", null)
                        .WithMany("EvidenceSources")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.ReportFieldNoteSourceRecord", b =>
                {
                    b.HasOne("SPINbuster.Infrastructure.Persistence.Records.ReportRecord", null)
                        .WithMany("FieldNoteSources")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.ReportRecord", b =>
                {
                    b.HasOne("SPINbuster.Infrastructure.Persistence.Records.InspectionSessionRecord", null)
                        .WithMany()
                        .HasForeignKey("InspectionSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SPINbuster.Infrastructure.Persistence.Records.ProjectRecord", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.ReportSectionRecord", b =>
                {
                    b.HasOne("SPINbuster.Infrastructure.Persistence.Records.ReportRecord", null)
                        .WithMany("Sections")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.SaveTransactionRecord", b =>
                {
                    b.HasOne("SPINbuster.Infrastructure.Persistence.Records.ReportRecord", null)
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.ContextManifestRecord", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.InspectionSessionRecord", b =>
                {
                    b.Navigation("EvidenceAttachments");

                    b.Navigation("FieldNotes");
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.KnowledgeDocumentRecord", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.KnowledgeDocumentRevisionRecord", b =>
                {
                    b.Navigation("Citations");
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.ModelRunRecord", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("SPINbuster.Infrastructure.Persistence.Records.ReportRecord", b =>
                {
                    b.Navigation("EvidenceSources");

                    b.Navigation("FieldNoteSources");

                    b.Navigation("Operations");

                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
